name: Build and Test Svelte Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build

  notify-discord:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code again
        uses: actions/checkout@v4

      - name: Calculate line changes
        id: line_changes
        run: |
          ADDED=$(git diff --stat HEAD~1 HEAD | awk '/changed/ {print $4}')
          DELETED=$(git diff --stat HEAD~1 HEAD | awk '/changed/ {print $6}')
          TOTAL=$((ADDED + DELETED))
          echo "ADDED=$ADDED" >> $GITHUB_ENV
          echo "DELETED=$DELETED" >> $GITHUB_ENV
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Count total lines of code
        id: total_lines
        run: |
          cloc . --json > cloc.json
          TOTAL_LINES=$(jq .SUM.code cloc.json)
          echo "TOTAL_LINES=$TOTAL_LINES" >> $GITHUB_ENV
          
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          LINES_ADDED: ${{ env.ADDED }}
          LINES_DELETED: ${{ env.DELETED }}
          LINES_TOTAL: ${{ env.TOTAL }}
          TOTAL_LINES_CODE: ${{ env.TOTAL_LINES }}
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "🚀 Ny uppdatering på main!",
              "description": "Senaste commit:\n**${{ github.event.head_commit.message }}**",
              "color": 65280,
              "fields": [
                { 
                  "name": "Gjort av", 
                  "value": "${{ github.event.head_commit.committer.name }}", 
                  "inline": true 
                },
                {
                  "name": "Antal rader kod ändrat", 
                  "value": "**Lagt till:** ${{ env.LINES_ADDED }}\n**Borttagna:** ${{ env.LINES_DELETED }}\n**Totalt:** ${{ env.LINES_TOTAL }}", 
                  "inline": false
                }, 
                {
                  "name": "Totalt antal rader kod i projektet",
                  "value": "**${{ env.TOTAL_LINES_CODE }} rader**",
                  "inline": false
                },
                { 
                  "name": "Klicka här för commit-detaljer", 
                  "value": "[Visa commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})", 
                  "inline": true 
                },
                { 
                  "name": "Repository", 
                  "value": "[Visa repository](https://github.com/${{ github.repository }})", 
                  "inline": false 
                }
              ],
              "footer": { 
                "text": "Pushat till main 🎉" 
              },
              "timestamp": "'"${{ github.event.head_commit.timestamp }}"'"
            }]
          }' \
          $DISCORD_WEBHOOK_URL
