name: Notify Discord

on:
  workflow_run:
    workflows: ["Build and Test Svelte Project"]
    types:
      - completed

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit info
        id: commit_info
        run: |
          # Extract commit details
          COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -n 1) 
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          COMMIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          # Set environment variables in the proper format for GitHub Actions
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE_HEADER}" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=${COMMIT_AUTHOR}" >> $GITHUB_ENV
          echo "COMMIT_BRANCH=${COMMIT_BRANCH}" >> $GITHUB_ENV

      - name: Calculate line changes
        id: line_changes
        run: |
          # Check if there is a previous commit
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            # Get the diff stats and capture the output
            DIFF_STATS=$(git diff --stat HEAD~1 HEAD)

            # Print the diff stats for debugging
            echo "Diff Stats: $DIFF_STATS"

            # Extract added and deleted lines using awk
            ADDED=$(echo "$DIFF_STATS" | awk '/changed/ {print $4}')
            DELETED=$(echo "$DIFF_STATS" | awk '/changed/ {print $6}')

            # Handle cases where ADDED or DELETED might not be found
            ADDED=${ADDED:-0}
            DELETED=${DELETED:-0}
            TOTAL=$((ADDED + DELETED))

            # Print extracted values for debugging
            echo "Added Lines: $ADDED"
            echo "Deleted Lines: $DELETED"
            echo "Total Lines Changed: $TOTAL"
          else
            echo "No previous commit found."
            ADDED=0
            DELETED=0
            TOTAL=0
          fi

          # Set the environment variables
          echo "ADDED=${ADDED}" >> $GITHUB_ENV
          echo "DELETED=${DELETED}" >> $GITHUB_ENV
          echo "TOTAL=${TOTAL}" >> $GITHUB_ENV

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Count total lines of code
        id: total_lines
        run: |
          cloc . --json > cloc.json
          TOTAL_LINES=$(jq .SUM.code cloc.json || echo 0)
          echo "TOTAL_LINES=${TOTAL_LINES}" >> $GITHUB_ENV

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "🚀 TCGG-Frontend!",
              "description": "Main uppdaterad.",
              "color": 8388736,
              "fields": [
                { 
                  "name": "Antal rader kod ändrat", 
                  "value": "**Lagt till:** '${{ env.ADDED }}'\n**Borttagna:** '${{ env.DELETED }}'\n**Totalt:** '${{ env.TOTAL }}'", 
                  "inline": false
                }, 
                {
                  "name": "Totalt antal rader kod i projektet",
                  "value": "**${{ env.TOTAL_LINES }} rader**",
                  "inline": false
                },
                {
                  "name": "Commitmeddelande",
                  "value": "**${{ env.COMMIT_MESSAGE }}**",
                  "inline": false
                },
                {
                  "name": "Utfördes av",
                  "value": "**${{ env.COMMIT_AUTHOR }}**",
                  "inline": true
                },
                {
                  "name": "Branch",
                  "value": "**${{ env.COMMIT_BRANCH }}**",
                  "inline": true
                },
                { 
                  "name": "Klicka här för commit-detaljer", 
                  "value": "[Visa commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})", 
                  "inline": true 
                },
                { 
                  "name": "Repository", 
                  "value": "[Visa repository](https://github.com/${{ github.repository }})", 
                  "inline": false 
                }
              ],
              "footer": { 
                "text": "Manuell körning av workflow 🎉 "
              },
              "timestamp": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"
            }]
          }' \
          $DISCORD_WEBHOOK_URL
